# Databricks notebook source
# MAGIC %md
# MAGIC # Load Synthetic Data into L2.2 Unified Model
# MAGIC Loads pre-generated synthetic CSV data directly into L2.2 dimension and fact tables.
# MAGIC The CSVs are generated by `scripts/generate_synthetic_data.py` and contain ~294K rows
# MAGIC with columns matching the L2.2 DDL schema exactly.
# MAGIC
# MAGIC **Tables loaded:**
# MAGIC - `dim_product` (500), `dim_material` (600), `dim_test_method` (400)
# MAGIC - `dim_site` (50), `dim_market` (30)
# MAGIC - `dim_specification` (2,000), `dim_specification_item` (16,000)
# MAGIC - `dim_batch` (5,000), `dim_instrument` (200), `dim_laboratory` (80)
# MAGIC - `fact_specification_limit` (120,000), `fact_analytical_result` (150,000)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Resolve CSV Path

# COMMAND ----------

import os

# In Databricks Repos, notebook path is under /Workspace/Repos/...
# The synthetic_data/ directory is at the repo root, two levels up from this notebook.
notebook_path = dbutils.notebook.entry_point.getDbutils().notebook().getContext().notebookPath().get()
repo_root = os.path.dirname(os.path.dirname(notebook_path))
csv_dir = f"/Workspace{repo_root}/synthetic_data"

# Fallback: if running locally or CSVs are in DBFS
if not os.path.exists(csv_dir):
    csv_dir = "/Workspace/synthetic_data"
if not os.path.exists(csv_dir):
    csv_dir = "file:/home/user/pharma-quality/synthetic_data"

print(f"CSV directory: {csv_dir}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Schema Definitions
# MAGIC Explicit schemas to ensure correct type casting from CSV strings to Delta column types.

# COMMAND ----------

from pyspark.sql.types import (
    StructType, StructField, StringType, IntegerType, LongType,
    DecimalType, BooleanType, DateType, TimestampType, FloatType, DoubleType
)

# Table loading order: dimensions first (no FK dependencies), then FK-dependent dims, then facts
TABLES = [
    # --- Independent dimensions (no FK to other L2.2 tables) ---
    {
        "csv": "dim_product.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_product",
        "schema": StructType([
            StructField("product_key", LongType()),
            StructField("product_id", StringType()),
            StructField("product_name", StringType()),
            StructField("inn_name", StringType()),
            StructField("brand_name", StringType()),
            StructField("product_family", StringType()),
            StructField("dosage_form_code", StringType()),
            StructField("dosage_form_name", StringType()),
            StructField("route_of_administration", StringType()),
            StructField("strength", StringType()),
            StructField("strength_value", DecimalType(12, 4)),
            StructField("strength_uom", StringType()),
            StructField("therapeutic_area", StringType()),
            StructField("nda_number", StringType()),
            StructField("shelf_life_months", IntegerType()),
            StructField("storage_conditions", StringType()),
            StructField("container_closure_system", StringType()),
            StructField("is_active", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "dim_material.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_material",
        "schema": StructType([
            StructField("material_key", LongType()),
            StructField("material_id", StringType()),
            StructField("material_name", StringType()),
            StructField("material_type_code", StringType()),
            StructField("material_type_name", StringType()),
            StructField("cas_number", StringType()),
            StructField("molecular_formula", StringType()),
            StructField("molecular_weight", DecimalType(10, 4)),
            StructField("inn_name", StringType()),
            StructField("compendial_name", StringType()),
            StructField("pharmacopoeia_grade", StringType()),
            StructField("grade", StringType()),
            StructField("supplier_name", StringType()),
            StructField("retest_period_months", IntegerType()),
            StructField("storage_requirements", StringType()),
            StructField("is_active", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "dim_test_method.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_test_method",
        "schema": StructType([
            StructField("test_method_key", LongType()),
            StructField("test_method_id", StringType()),
            StructField("test_method_name", StringType()),
            StructField("test_method_number", StringType()),
            StructField("test_method_version", StringType()),
            StructField("method_type", StringType()),
            StructField("analytical_technique", StringType()),
            StructField("compendia_reference", StringType()),
            StructField("detection_limit", DecimalType(18, 6)),
            StructField("quantitation_limit", DecimalType(18, 6)),
            StructField("validation_status", StringType()),
            StructField("validation_date", DateType()),
            StructField("is_validated", BooleanType()),
            StructField("is_active", BooleanType()),
            StructField("effective_from", DateType()),
            StructField("effective_to", DateType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "dim_site.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_site",
        "schema": StructType([
            StructField("site_key", LongType()),
            StructField("site_id", StringType()),
            StructField("site_code", StringType()),
            StructField("site_name", StringType()),
            StructField("site_type", StringType()),
            StructField("address_line", StringType()),
            StructField("city", StringType()),
            StructField("state_province", StringType()),
            StructField("country_code", StringType()),
            StructField("country_name", StringType()),
            StructField("regulatory_region", StringType()),
            StructField("gmp_status", StringType()),
            StructField("gmp_certificate_number", StringType()),
            StructField("fda_fei_number", StringType()),
            StructField("last_inspection_date", DateType()),
            StructField("last_inspection_outcome", StringType()),
            StructField("is_active", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "dim_market.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_market",
        "schema": StructType([
            StructField("market_key", LongType()),
            StructField("market_code", StringType()),
            StructField("market_name", StringType()),
            StructField("country_code", StringType()),
            StructField("country_name", StringType()),
            StructField("region_code", StringType()),
            StructField("region_name", StringType()),
            StructField("regulatory_authority", StringType()),
            StructField("primary_pharmacopoeia", StringType()),
            StructField("market_status", StringType()),
            StructField("marketing_auth_number", StringType()),
            StructField("is_active", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    # --- FK-dependent dimensions ---
    {
        "csv": "dim_specification.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_specification",
        "schema": StructType([
            StructField("spec_key", LongType()),
            StructField("source_specification_id", StringType()),
            StructField("spec_number", StringType()),
            StructField("spec_version", StringType()),
            StructField("spec_title", StringType()),
            StructField("spec_type_code", StringType()),
            StructField("spec_type_name", StringType()),
            StructField("product_key", LongType()),
            StructField("material_key", LongType()),
            StructField("site_key", LongType()),
            StructField("market_key", LongType()),
            StructField("status_code", StringType()),
            StructField("status_name", StringType()),
            StructField("stage_code", StringType()),
            StructField("stage_name", StringType()),
            StructField("ctd_section", StringType()),
            StructField("compendia_reference", StringType()),
            StructField("effective_start_date", DateType()),
            StructField("effective_end_date", DateType()),
            StructField("effective_start_date_key", IntegerType()),
            StructField("effective_end_date_key", IntegerType()),
            StructField("approval_date", DateType()),
            StructField("approval_date_key", IntegerType()),
            StructField("approver_name", StringType()),
            StructField("approved_by", StringType()),
            StructField("supersedes_spec_id", StringType()),
            StructField("supersedes_spec_key", LongType()),
            StructField("is_current", BooleanType()),
            StructField("valid_from", TimestampType()),
            StructField("valid_to", TimestampType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "dim_specification_item.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_specification_item",
        "schema": StructType([
            StructField("spec_item_key", LongType()),
            StructField("source_spec_item_id", StringType()),
            StructField("spec_key", LongType()),
            StructField("test_method_key", LongType()),
            StructField("uom_key", IntegerType()),
            StructField("test_code", StringType()),
            StructField("test_name", StringType()),
            StructField("analyte_code", StringType()),
            StructField("test_category_code", StringType()),
            StructField("test_category_name", StringType()),
            StructField("test_subcategory", StringType()),
            StructField("criticality", StringType()),
            StructField("sequence_number", IntegerType()),
            StructField("is_required", BooleanType()),
            StructField("is_compendial", BooleanType()),
            StructField("is_stability_indicating", BooleanType()),
            StructField("reporting_type", StringType()),
            StructField("result_precision", IntegerType()),
            StructField("compendia_test_ref", StringType()),
            StructField("stage_applicability", StringType()),
            StructField("reporting_threshold", DecimalType(18, 6)),
            StructField("identification_threshold", DecimalType(18, 6)),
            StructField("qualification_threshold", DecimalType(18, 6)),
            StructField("is_current", BooleanType()),
            StructField("valid_from", TimestampType()),
            StructField("valid_to", TimestampType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "dim_batch.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_batch",
        "schema": StructType([
            StructField("batch_key", LongType()),
            StructField("batch_number", StringType()),
            StructField("batch_system_id", StringType()),
            StructField("product_key", LongType()),
            StructField("site_key", LongType()),
            StructField("batch_type", StringType()),
            StructField("manufacturing_date", DateType()),
            StructField("expiry_date", DateType()),
            StructField("retest_date", DateType()),
            StructField("batch_size", DecimalType(18, 4)),
            StructField("batch_size_unit", StringType()),
            StructField("yield_pct", DecimalType(8, 4)),
            StructField("batch_status", StringType()),
            StructField("disposition_date", DateType()),
            StructField("packaging_configuration", StringType()),
            StructField("is_active", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "dim_instrument.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_instrument",
        "schema": StructType([
            StructField("instrument_key", LongType()),
            StructField("instrument_id", StringType()),
            StructField("instrument_name", StringType()),
            StructField("instrument_type", StringType()),
            StructField("serial_number", StringType()),
            StructField("manufacturer", StringType()),
            StructField("qualification_status", StringType()),
            StructField("calibration_due_date", DateType()),
            StructField("location", StringType()),
            StructField("is_active", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "dim_laboratory.csv",
        "table": "pharma_quality.l2_2_unified_model.dim_laboratory",
        "schema": StructType([
            StructField("laboratory_key", LongType()),
            StructField("laboratory_id", StringType()),
            StructField("laboratory_name", StringType()),
            StructField("laboratory_type", StringType()),
            StructField("site_key", LongType()),
            StructField("accreditation_status", StringType()),
            StructField("is_active", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    # --- Fact tables ---
    {
        "csv": "fact_specification_limit.csv",
        "table": "pharma_quality.l2_2_unified_model.fact_specification_limit",
        "schema": StructType([
            StructField("spec_limit_key", LongType()),
            StructField("spec_key", LongType()),
            StructField("spec_item_key", LongType()),
            StructField("limit_type_key", IntegerType()),
            StructField("uom_key", IntegerType()),
            StructField("effective_start_date_key", IntegerType()),
            StructField("effective_end_date_key", IntegerType()),
            StructField("lower_limit_value", DecimalType(18, 6)),
            StructField("upper_limit_value", DecimalType(18, 6)),
            StructField("target_value", DecimalType(18, 6)),
            StructField("limit_range_width", DecimalType(18, 6)),
            StructField("lower_limit_operator", StringType()),
            StructField("upper_limit_operator", StringType()),
            StructField("limit_text", StringType()),
            StructField("limit_description", StringType()),
            StructField("limit_basis", StringType()),
            StructField("stage_code", StringType()),
            StructField("stability_time_point", StringType()),
            StructField("stability_condition", StringType()),
            StructField("calculation_method", StringType()),
            StructField("sample_size", IntegerType()),
            StructField("last_calculated_date_key", IntegerType()),
            StructField("is_in_filing", BooleanType()),
            StructField("regulatory_basis", StringType()),
            StructField("source_limit_id", StringType()),
            StructField("is_current", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
    {
        "csv": "fact_analytical_result.csv",
        "table": "pharma_quality.l2_2_unified_model.fact_analytical_result",
        "schema": StructType([
            StructField("analytical_result_key", LongType()),
            StructField("batch_key", LongType()),
            StructField("spec_key", LongType()),
            StructField("spec_item_key", LongType()),
            StructField("condition_key", IntegerType()),
            StructField("timepoint_key", IntegerType()),
            StructField("instrument_key", LongType()),
            StructField("laboratory_key", LongType()),
            StructField("uom_key", IntegerType()),
            StructField("test_date_key", IntegerType()),
            StructField("result_value", DecimalType(18, 6)),
            StructField("result_text", StringType()),
            StructField("result_status_code", StringType()),
            StructField("percent_label_claim", DecimalType(18, 6)),
            StructField("reported_lower_limit", DecimalType(18, 6)),
            StructField("reported_upper_limit", DecimalType(18, 6)),
            StructField("reported_target", DecimalType(18, 6)),
            StructField("is_oos", BooleanType()),
            StructField("is_oot", BooleanType()),
            StructField("sample_type", StringType()),
            StructField("replicate_number", IntegerType()),
            StructField("analyst_name", StringType()),
            StructField("reviewer_name", StringType()),
            StructField("lab_name", StringType()),
            StructField("report_id", StringType()),
            StructField("coa_number", StringType()),
            StructField("stability_study_id", StringType()),
            StructField("source_result_id", StringType()),
            StructField("is_current", BooleanType()),
            StructField("load_timestamp", TimestampType()),
        ]),
    },
]

# COMMAND ----------

# MAGIC %md
# MAGIC ## Load CSVs into L2.2 Tables

# COMMAND ----------

results = []

for tbl in TABLES:
    csv_path = f"{csv_dir}/{tbl['csv']}"
    table_name = tbl["table"]

    df = (
        spark.read
        .option("header", "true")
        .option("nullValue", "")
        .option("timestampFormat", "yyyy-MM-dd'T'HH:mm:ss.SSSSSS")
        .schema(tbl["schema"])
        .csv(csv_path)
    )

    row_count = df.count()
    df.write.format("delta").mode("append").saveAsTable(table_name)
    results.append((tbl["csv"], table_name.split(".")[-1], row_count))
    print(f"  Loaded {row_count:>8,} rows into {table_name}")

print("\nSynthetic data loading complete.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Verify Loaded Counts

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT 'dim_product' AS table_name, COUNT(*) AS rows FROM pharma_quality.l2_2_unified_model.dim_product
# MAGIC UNION ALL SELECT 'dim_material', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_material
# MAGIC UNION ALL SELECT 'dim_test_method', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_test_method
# MAGIC UNION ALL SELECT 'dim_site', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_site
# MAGIC UNION ALL SELECT 'dim_market', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_market
# MAGIC UNION ALL SELECT 'dim_specification', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_specification
# MAGIC UNION ALL SELECT 'dim_specification_item', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_specification_item
# MAGIC UNION ALL SELECT 'dim_batch', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_batch
# MAGIC UNION ALL SELECT 'dim_instrument', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_instrument
# MAGIC UNION ALL SELECT 'dim_laboratory', COUNT(*) FROM pharma_quality.l2_2_unified_model.dim_laboratory
# MAGIC UNION ALL SELECT 'fact_specification_limit', COUNT(*) FROM pharma_quality.l2_2_unified_model.fact_specification_limit
# MAGIC UNION ALL SELECT 'fact_analytical_result', COUNT(*) FROM pharma_quality.l2_2_unified_model.fact_analytical_result
# MAGIC ORDER BY table_name;
